function LX = laplace_krat(X)

LX = -4*X + [zeros(size(X,1),1),X(:,1:end-1)]+...
     [X(:,2:end),zeros(size(X,1),1)] +...
     [zeros(1,size(X,2)); X(1:end-1,:)]+...
     [X(2,end); zeros(1,size(X,2))];