* Aproksimacija s polinomi Čebiševa
Weierstrassov izrek pravi, da lahko poljubno zvezno funkcijo na končnem
intervalu enakomerno na vsem intervalu aproksimiramo s polinomi. Polinom dane
stopnje, ki neko funkcijo najbolje aproksimira je težko poiskati. Z razvojem
funkcije po ortogonalnih polinomih Čebiševa, pa se optimalni aproksimaciji zelo
približamo. Naj bo $f:[-1,q]\to \mathbb{R}$ zvezna funkcija. Potem lahko $f$
zapišemo z neskončno vrsto 

$$f(t)=\sum_{n=0}^\infty a_nT_n(t),$$

kjer so $T_n$ polinomi Čebiševa. Polinomi Čebiševa so definirani z relacijo

$$T_n(\cos(\phi))=\cos(n\phi)$$

in zadoščajo dvočlenski rekurzivni enačbi

$$T_{n+1}(x)=2xT_n(x)-T_{n-1}(x).$$

Namesto cele vrste, lahko obdržimo le prvih nekaj členov in funkcijo
*aproksimiramo* s funkcijo oblike 

$$f(x)\sim \sum_{n=0}^N a_nT_n(x).$$

Iščemo torej koeficiente funkcije $f(x)$ v razvoju po $T_n$.
** Razvoj po Čebiševih polinomih 
\begin{equation}
a_k = \frac{2}{\pi}\int_{-1}^1 \frac{f(x) T_k(x)}{\sqrt{1-x^2}}dx,
\end{equation}
kjer za $k=0$ faktor $\frac{2}{\pi}$ zemenjamo z $\frac{1}{\pi}$. Na srečo je
mogoče koeficiente $a_k$ izračunati izjemno učinkovito z diskretno Fourierovo
kosinusno transformacijo funkcijskih vrednosti v Čebiševih interpolacijskih
točkah. 

Napisali bomo dve funkciji `y = chebval(T,x)` in `T = chebfun(fun,n)`.
#+BEGIN_SRC octave :tangle chebval.m
% funkcija y = chebval(p,x) izračuna vrednost polinoma, ki je podan v Čebiševi bazi
% p(x) = p(1)T0(x) + p(2)T1(x) + ... + p(n+1)Tn(x)
function y = chebval(p,x)
  n = length(p); % stopnja polinoma
  Tp = ones(size(x)); T = x;
  if n==0
    y = p(end)*Tp;
    return
  end
  y = p(1)*Tp+p(2)*T;
  if n==1
   return
  end

  for i=3:n
    Tn = 2*x.*T - Tp;
    Tp = T;
    T = Tn;
    y = y + p(i)*T;
  end
endfunction
%!test
#! p = [2 0 -1]; t = linspace(-1,1);
%! assert(chebval([1,0,0],t),polyval([2 0 -1],t),eps)

#+END_SRC

#+BEGIN_SRC octave :tangle chebfun.m
  % funkcija fp = chebfun(fun,n) 
  % izračuna razcep funkcije fun na intervalu [-1,1]
  % po Čebiševih polinomih stopnje največ n
  function fp = chebfun(fun,n)
    fi = pi*linspace(0.5/n,1-0.5/n,n);
    x = cos(fi); % ničle n-tega Čebiševega polinoma
    f = fun(x); % vrednosti funkcije
    # diskretna cosinusna transformacija
    pf = zeros(1,4*n);
    pf(2:2:2*n) = f; pf(4*n:-2:2*n+1) = f;
    dctf = fft(pf)(1:n);
    fp = dctf/n;
    fp(1) = fp(1)/sqrt(2);
  endfunction
  %!assert(chebfun(@(x) polyval([4 2 -3 -1],x), 4), [0 0 1 1],2*eps)

  %!demo
  %! x = linspace(-1,1);
  %! T = chebfun(@sin,9);
  %! plot(x,sin(x)-chebval(T,x))
  %! title("Razlika med sin(x) in aproksimacijo z 9 členi Čebiševe vrste.")
#+END_SRC
[[http://www.chebfun.org/][Knjižnica `chebfun`]]

[[http://arxiv.org/pdf/1409.2789v2.pdf][THE AUTOMATIC SOLUTION OF PARTIAL DIFFERENTIAL 
EQUATIONS USING A GLOBAL SPECTRAL METHOD]]

[[http://www.chebfun.org/ATAP/][Trefetnova knjiga]]
