* Aproksimacija z linearnim modelom
** Linearni model
V znanosti pogosto želimo opisati odvisnost dveh količin npr. kako se spreminja
koncentracija $\mathrm{CO}_2$ v odvisnosti od časa. Matematičnemu opisu
povezave med dvema ali več količinami pravimo *matematični model*. Primer modela
je Hookov zakon za vzmet, ki pravi, da je sila vzmeti $F$ sorazmerna z raztezkom
$x$: 
\[F=k x\]
Model povezuje dve količini silo $F$ in raztezek $x$. Poleg tega Hookov zakon
vpelje še koeficient vzmeti $k$. Koeficientu $k$ pravimo *parameter modela* in
ga lahko določimo za vsako vzmet posebej z meritvami sile in raztezka.

Najpreporstejši je *linearni model*, pri katerem odvisno količino $y$ zapišemo
kot linearno kombinacijo baznih funkcij $\phi_j(x)$ neodvisne spremenljivke $x$:  
\begin{equation}
  y(x) = M(p,x) = p_1\phi_1(x) + p_2\phi_2(x) + \ldots + p_k \phi_k(x).
\end{equation}
Koeficientom $p_j$ pravimo parametri modela in jih določimo na podlagi meritev.
Znanstveniki hočejo model, pri katerem imajo parametri $p_i$ preprosto
interpretacijo in pomagajo pri razumevanju pojava, ki ga opisujejo. Zato so
bazne funkcije pogosto elementarne funkcije, pri katerih je jasno razvidna narava
odvisnosti. 
*** Metoda najmanjših kvadratov
Koeficiente modela, ki najbolje opisujejo izmerjene podatke lahko poiščemo z
metodo najmanjših kvadratov. Napišemo najprej pogoje, ki bi jim zadoščali
parametri, če bi izmerjeni podatki povsem sledili modelu. Za vsako meritev
$y_i=y(x_i)$ bi bila vrednost odvisne količine $y_i$ natanko enaka vrednosti, ki
jo predvidi model $M(p,x_i)$. To predpostavko lahko zapišemo s sistemom enačb
\begin{equation}\label{eq:sistem}
y_i = M(p,x_i) = p_1\phi_1(x_i)+\ldots p_k\phi_k(x_k)
\end{equation}
Neznanke v zgornjem sistemu so parametri $p_j$ in za *linearni model* so enačbe
linearne. To je tudi ena glavnih prednosti linearnega modela.
Meritve redko povsem sledijo modelu, zato sistem (\ref{eq:sistem}) v splošnem ni
rešljiv, saj je meritev običajno več kot je parametrov sistema. Sistem
(\ref{eq:sistem}) je *predoločen*. Lahko pa poiščemo vrednosti parametrov $p_j$
pri katerih bo razlika med meritvami in modelom kar se da majhna. Izkaže se, da
je najboljša mera za odstopanje modela od podatkov kar vsota kvadratov razlik
med meritvami in napovedjo modela:
\begin{equation}\label{eq:minkvad}
(y_1-M(p,x_1))^2+\ldots + (y_n-M(p,x_n))^2 = \sum_{i=1}^n (y_i + M(p,x_i))^2
\end{equation}
Sistem (\ref{eq:sistem}) lahko zapišemo v matrični obliki 
\[A\mathbf{p} = \mathbf{y},\]
kjer so stolpci matrike sistema enaki vrednostim baznih funkcij
\[A = \begin{bmatrix}
\phi_1(x_1) & \phi_2(x_1) & \ldots &\phi_k(x_1)\\
\phi_1(x_2) & \phi_2(x_2) & \ldots &\phi_k(x_2)\\
\vdots & \vdots & \ddots &\vdots \\
\phi_1(x_n) & \phi_2(x_n) & \ldots &\phi_k(x_n)\\
\end{bmatrix} \]
in stolpec desnih strani je enak meritvam $\mathbf{y} = [y_1,y_2,\ldots,
y_n]^\mathsf{T}$. Pogoj najmanjših kvadratov razlik (\ref{eq:minkvad}) za
optimalne vrednosti parametrov $\mathbf{p}_{opt}$ lahko
sedaj zapišemo s kvadratno vektorsko normo
#+BEGIN_SRC latex :exports none
\DeclareMathOperator*{\argmin}{arg\,min}
#+END_SRC
\begin{equation}
\mathbf{p}_{opt} = \mathrm{argmin}_{\mathbf{p}} \left\|A\mathbf{p}-\mathbf{y}\right\|_2^2.
\end{equation} 
** Opis sprememb koncentracije CO2
Na observatoriju \href{http://www.esrl.noaa.gov/gmd/obop/mlo/}{Mauna Loa} na
Hawaiih že leta spremljajo koncentracijo $\mathrm{CO}_2$ v ozračju. Časovni potek
koncentracije $\COdva$ matematično opišemo kot funkcijo koncentracije v
odvisnosti od časa 
\begin{equation}
  y=\mathrm{CO}_2(t).
\end{equation}
Model, ki dobro opisuje spremembe $\mathrm{CO}_2$ lahko sestavimo iz kvadratne
funcije, ki opisuje naraščanje letnih povprečij in periodičnega dela, ki opiše
nihanja med letom:   
\begin{equation}
  \label{eq:model}
\mathrm{CO}_2(t)= p_1 + p_2 t +p_3t^2+p_4\sin(2\pi t)+p_5\cos(2\pi t). 
\end{equation}
Čas $t$ naj bo podan v letih. Predoločeni sistem (\ref{eq:sistem}), ki ga dobimo
za naš model ima $n\times 5$ matriko sistema
\[A = \begin{bmatrix}
1 & t_1 & t_1^2 & \sin(2\pi t_1) & \cos(2\pi t_1)\\
1 & t_2 & t_2^2 & \sin(2\pi t_2) & \cos(2\pi t_2)\\
\vdots & \vdots & \vdots &\vdots &\vdots\\
1 & t_n & t_n^2 & \sin(2\pi t_n) & \cos(2\pi t_n)\\
\end{bmatrix} \]
*** Normalni sistem
*** QR razcep
*** Vgrajena funkcija
