#+TITLE: Četrta domača naloga
#+SUBTITLE: Numerična matematika
#+LANGUAGE: sl
#+LATEX_HEADER: \usepackage[slovene]{babel}

* Navodila

Nalogo rešite na *10 decimalk* (z relativno natančnostjo $\mathbf{10^{-10}}$). 
Uporabite lahko le osnovne operacije, vgrajene osnovne matematične funkcije
$\exp$, $\sin$, $\cos$ ..., osnovne operacije z matrikami in razcepe matrik. Vse
ostale algoritme morate implementirati sami. Ocena bo odvisna tudi od
*učinkovitosti* vašega algoritma. 


Vsaka datoteka naj vsebuje komentar s pomočjo za funkcijo, teste v obliki 
#+BEGIN_SRC octave
%!test
%! assert ...
#+END_SRC
in predstavitveno kodo funkcije v obliki
#+BEGIN_SRC octave
%!demo
%! # Primer uporabe funkcije
%! y = funkcija(1,2,3) ... 
#+END_SRC
Če uporabljate drug programski jezik, ravno tako kodi dodajte osnovno
dokumentacijo, teste in demo.

* Težje naloge
** Ničle Airyjeve funkcije
Airyjeva funkcija je dana kot rešitev začetnega problema
\[
Ai''(x)-x\,Ai(x)=0,\quad Ai(0)=\frac{1}{3^\frac{2}{3}\Gamma\left(\frac{2}{3}\right)}\,Ai'(0)=-\frac{1}{3^\frac{1}{3}\Gamma\left(\frac{1}{3}\right)}.
\]

Poiščite čim več ničel funkcije \(Ai\) na 10 decimalnih mest natančno. Ni
dovoljeno uporabiti vgrajene funkcijo za reševanje diferencialnih enačb.
Vgrajeno Airyjevo funkcijo pa lahko uporabite, da preverite ali ste res dobili
pravo ničlo.
*** Namig
 Za računanje vrednosti \(y(x)\) uporabite Magnusovo metodo reda 4, pri kateri
 nov približek \(\mathbf{Y}_{k+1}\) dobimo takole: 
\[\begin{array}{ccc}
 A_1&=&A\left(x_k+\left(\frac{1}{2}-\frac{\sqrt{3}}{6}\right)h\right)\\ 
A_2&=&A\left(x_k+\left(\frac{1}{2}+\frac{\sqrt{3}}{6}\right)h\right)\\ 
\sigma_{k+1}&=&\frac{h}{2}(A_1+A_2)-\frac{\sqrt{3}}{12}h^2[A_1,A_2]\\ 
\mathbf{Y}_{k+1}&=&\exp(\sigma_{k+1})\mathbf{Y}_k.
 \end{array}\] 

Izraz \([A,B]\) je komutator dveh matrik in ga izračunamo takole:
\([A,B]=AB-BA\). Eksponentno funkcijo na matriki (\(\exp(\sigma_{k+1})\)) pa v
 matlabu dobite z ukazom expm.
** Dolžina implicinto podane krivulje
Poiščite približek za dolžino krivulje, ki je dana implicitno z enačbama
\begin{align*}
F_1(x,y,z)&=x^4+y^2/2+z^2=12\\
F_2(x,y,z)&=x^2+y^2-4z^2=8.
\end{align*}
Krivuljo lahko poiščete kot rešitev diferencialne enačbe
\[
\dot{\mathbf{x}}(t) = \nabla F_1\times \nabla F_2.
\]
** Perioda limitnega cikla
Poiščite periodo limitnega cikla za diferencialno enačbo
\[x''(t)-4(1-x^2)x'(t)+x=0\]
na 10 decimalk natančno.
*** Rešitev :noexport:
Poiščemo limitni cikel
#+BEGIN_SRC octave :session
lsode_options("absolute tolerance",1e-14);
fun = @(y,t) [y(2);4*(1-y(1)^2)*y(2)-y(1)];
t=linspace(0,100); Y = lsode(fun,[1;1],t);
Y(end,:)
#+END_SRC

#+RESULTS:
| 1.964136027067184 | -0.1688964692664729 |

Nato poiščemo periodo
#+BEGIN_SRC octave :session
Y0 = Y(end,:);
t0 = 0; tk = 10; 
for i=1:10
  Y = lsode(fun,Y(end,:),[t0,tk]);
  t0 = tk;
  tk = tk - (Y(end,1)-Y0(1,1))/Y(end,2);
end
[tk,norm(Y(end,:)-Y0(1,:))]
#+END_SRC

#+RESULTS:
| 10.2035236909362 | 3.751443600208404e-13 |
** Obhod lune
Sondo Appolo pošljite iz Zemljine orbite na tir z vrnitvijo brez potiska (free-return trajectory),
ki obkroži Luno in se vrne nazaj v Zemljino orbito. Rešujte sistem
diferencialnih enačb, ki ga dobimo v koordinatnem sistemu, v katerem Zemlja in
Luna mirujeta (omejen krožni problem treh teles). Naloge ni potrebno reševati na
10 decimalk. 
*** Omejen krožni problem treh teles
 Označimo z $M$ maso Zemlje in z $m$ maso Lune. Ker je masa sonde zanemarljiva,
  Zemlja in Luna kro"zita okrog skupnega masnega sredi"s"ca.  Ena"cbe gibanja zapišemo v vrte"cem 
  koordinatnem sistemu, kjer masi $M$ in $m$ mirujeta. Ozna"cimo
  \[
 	 \mu = \frac{m}{M+m} \quad \textrm{ ter } \quad \bar{\mu} = 1 - \mu = \frac{M}{M+m} \textrm{. }
  \]
  V brezdimenzijskih koordinatah (dol"zinska enota je kar razdalja med masama $M$ in $m$) postavimo maso $M$ v to"cko $(-\mu,0,0)$, maso $m$ pa v to"cko $(\bar{\mu},0,0)$. Ozna"cimo z $R$ in $r$ oddaljenost 
  satelita s polo"zajem $(x,y,z)$ od mas $M$ in $m$, tj.
 #+BEGIN_EXPORT latex
  \begin{align*}
 	 R &= R(x,y,z) = \sqrt{(x+\mu)^2 + y^2 + z^2}, \\
	 r &= r(x,y,z) = \sqrt{(x-\bar{\mu})^2 + y^2 + z^2}.
  \end{align*}
  Ena"cbe gibanja sonde so potem:
  \begin{align*}
 	 \ddot{x} &= x + 2 \dot{y} - \frac{\bar{\mu}}{R^3} (x + \mu) - \frac{\mu}{r^3} (x - \bar{\mu}), \\
	 \ddot{y} &= y - 2 \dot{x} - \frac{\bar{\mu}}{R^3} y - \frac{\mu}{r^3} y, \\
	 \ddot{z} &= - \frac{\bar{\mu}}{R^3} z - \frac{\mu}{r^3} z.
  \end{align*}
 #+END_EXPORT 
*** Rešitev :noexport:
Omejen problem treh teles v ravnini
#+BEGIN_EXPORT latex
\begin{eqnarray}
 \ddot{x} &=& x + 2\dot{y} - \frac{\hat{\mu}}{R^3}(x+\mu)-\frac{\mu}{r^3}(x-\hat{\mu})\\
 \ddot{y} &=& y - 2\dot{x} - \frac{\hat{mu}}{R^3}y- \frac{\mu}{r^3}y,
\end{eqnarray}
kjer je 
\begin{eqnarray}
R &=& \sqrt{(x+\mu)^2+y^2}\\
r &=& \sqrt{(x-\hat{\mu})^2+y^2}
\end{eqnarray}
in $\mu = \frac{m}{M+m}$ ter $\hat{\mu} = 1-\mu = \frac{M}{M+m}$.
#+END_EXPORT

| Zemlja        | $5.97\cdot 10^24$kg |
| Luna          | $7.35\cdot 10^22$kg |
| Zemlja-Luna   | $384400$km          |
| Orbita Zemlja | $6563$km            |
| Orbita Luna   | $1849$km            |

#+BEGIN_SRC julia
  function tbs(r,p)
    x,y,dx,dy = r
    M,m = p
    mu = m/(M+m); muh = 1 - mu
    R = sqrt((x+mu)^2+y^2)
    r = sqrt((x-muh)^2+y^2)
    ddx = x + 2dy - muh/R^3(x+mu) - mu/r^3(x-muh)
    ddy = y -2dx - muh/R^3y - mu/r^3y
    return [dx,dy,ddx,ddy]
  end

#+END_SRC
#+BEGIN_SRC julia
     function rk4(f,t0,y0,tk,n)
      t = linspace(t0,tk,n+1)
      h = t[2]-t[1]
      y = zeros(size(y0,1),n)
   for i=1:n
      k1 = h*f(t(i),y(:,i);
      k2 = h*f(t(i)+h/2,y(:,i)+k1/2);
      k3 = h*f(t(i)+h/2,y(:,i)+k2/2);
      k4 = h*f(t(i)+h,y(:,i)+k3);                                                                     X = [X x];
      y(:,i+1) = y(:,1) + (k1+k2+k2+k3+k3+k4)/6;  
     end
             return t,y
  end
#+END_SRC
* Lažja naloga (ocena največ 9)
Naloga je namenjena tistim, ki jih je strah eksperimentiranja ali pa za to
preprosto nimajo interesa ali časa. 

** Matematično nihalo
Kotni odmik \(\theta(t)\) (v radianih) pri nedušenem nihanju nitnega nihala opišemo z diferencialno enačbo 
\[{g\over l}\sin(\theta(t))+\theta^{\prime\prime}(t)=0, \quad \theta(0)=
\theta_0,\ \theta^{\prime}(0)=\theta^{\prime}_0,\] 
kjer je \(g=9.80665m/s^2\) težni pospešek in \(l\) dolžina nihala. Napišite
funkcijo =nihalo=, ki računa odmik nihala ob določenem času. Enačbo drugega reda
prevedite na sistem prvega reda in računajte z metodo Runge-Kutta četrtega reda:
\[\begin{array}{ccc}  
k_1& = &h\,f(x_n,y_n)\\ 
k_2& = & h\,f(x_n+h/2,y_n+k_1/2)\\ 
k_3& = & h\,f(x_n+h/2,y_n+k_2/2)\\ 
k_4& = & h\,f(x_n+h,y_n+k_3)\\ 
y_{n+1}& = & y_n+(k_1+2k_2+2k_3+k_4)/6. \end{array}\] 

Klic funkcije naj bo oblike =odmik=nihalo(l,t,theta0,dtheta0,n)= 
 - kjer je =odmik= enak odmiku nihala ob času =t=,
 - dolžina nihala je =l=,
 - začetni odmik (odmik ob času \(0\)) je =theta0=
 - in začetna kotna hitrost (\(\theta'(0)\)) je =dtheta0=,
 - interval \([0,t]\) razdelimo na =n= podintervalov enake dolžine.

Primerjajte rešitev z nihanjem harmoničnega nihala. Za razliko od harmoničnega
nihala (sinusno nihanje), je pri matematičnem nihalu nihajni čas odvisen od
začetnih pogojev (energije). Narišite graf, ki predstavlja, kako se nihajni čas
spreminja z energijo nihala.
